### ISSUE TITLE
Almost all fails at    7-build-project-jobs

### ISSUE THREAD

**Issue by kevinrz6** [dd010101/vyos-jenkins#46] opened 2024-08-03 05:00 UTC
It was all good until step   7-build-project-jobs    in the automated method. Everything except the Linux-Kernel is failing.
What is the best method to debug this?

root@debian12:/opt/vyos-jenkins# ./7-build-project-jobs.sh
#################################################
# Unofficial VyOS package mirror installer v1.0 #
#################################################

-- Currently executing '7-build-project-jobs.sh' --

[ OK ] Connected to Jenkins successfully.

Building jobs in Jenkins...
Total number of jobs: 93
Concurrent jobs: 8 (Can be overridden by setting the CONCURRENT_JOBS_COUNT environment variable)

[   Failed!   ] Package: aws-gateway-load-balancer-tunnel-handler - Branch: sagitta
[   Failed!   ] Package: ddclient - Branch: sagitta
[   Failed!   ] Package: dropbear - Branch: equuleus
[   Failed!   ] Package: dropbear - Branch: sagitta
[   Failed!   ] Package: ethtool - Branch: sagitta
[   Failed!   ] Package: frr - Branch: equuleus
[   Failed!   ] Package: frr - Branch: sagitta
[   Failed!   ] Package: hostap - Branch: equuleus
[   Failed!   ] Package: hostap - Branch: sagitta
[   Failed!   ] Package: hsflowd - Branch: sagitta
[   Failed!   ] Package: hvinfo - Branch: equuleus
[   Failed!   ] Package: hvinfo - Branch: sagitta
[   Failed!   ] Package: ipaddrcheck - Branch: equuleus
[   Failed!   ] Package: ipaddrcheck - Branch: sagitta
[   Failed!   ] Package: iproute2 - Branch: equuleus
[   Failed!   ] Package: isc-dhcp - Branch: sagitta
[   Failed!   ] Package: keepalived - Branch: equuleus
[   Failed!   ] Package: keepalived - Branch: sagitta
[   Failed!   ] Package: libnss-mapuser - Branch: equuleus
[   Failed!   ] Package: libnss-mapuser - Branch: sagitta
[   Failed!   ] Package: libnss-tacplus - Branch: sagitta
[   Failed!   ] Package: libpam-radius-auth - Branch: equuleus
[   Failed!   ] Package: libpam-radius-auth - Branch: sagitta
[   Failed!   ] Package: libvyosconfig - Branch: equuleus
[   Failed!   ] Package: libvyosconfig - Branch: sagitta
[   Running   ] Package: linux-kernel - Branch: equuleus
[   Running   ] Package: linux-kernel - Branch: sagitta
[   Failed!   ] Package: live-boot - Branch: equuleus
[   Failed!   ] Package: live-boot - Branch: sagitta
[   Failed!   ] Package: mdns-repeater - Branch: equuleus
[   Failed!   ] Package: minisign - Branch: equuleus
[   Failed!   ] Package: ndppd - Branch: sagitta

**Comment by dd010101** [comment] 2024-08-03 05:07
Please follow the [Something is wrong](https://github.com/dd010101/vyos-jenkins#something-is-wrong).

**Comment by marekm72** [comment] 2024-08-04 10:05
```
debian@debian:~$ sudo journalctl --no-pager -b -u uncron.service
[sudo] password for debian: 
Aug 04 05:30:57 debian systemd[1]: Started uncron.service - Command Queue Service.
Aug 04 05:30:57 debian uncron[15984]: Starting uncron
Aug 04 05:30:57 debian uncron[15984]: Fatal error: exception Unix.Unix_error(Unix.EACCES, "bind", "")
Aug 04 05:30:57 debian uncron[15984]: Raised by primitive operation at Lwt_unix.self_result in file "src/unix/lwt_unix.cppo.ml", line 246, characters 14-31
Aug 04 05:30:57 debian uncron[15984]: Re-raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3123, characters 20-29
Aug 04 05:30:57 debian uncron[15984]: Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 27, characters 10-20
Aug 04 05:30:57 debian uncron[15984]: Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 106, characters 8-13
Aug 04 05:30:57 debian uncron[15984]: Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 112, characters 4-13
Aug 04 05:30:57 debian uncron[15984]: Called from Dune__exe__Uncron in file "src/uncron.ml", line 153, characters 4-32
Aug 04 05:30:57 debian systemd[1]: uncron.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 04 05:30:57 debian systemd[1]: uncron.service: Failed with result 'exit-code'.
Aug 04 05:31:02 debian systemd[1]: uncron.service: Scheduled restart job, restart counter is at 1.
Aug 04 05:31:02 debian systemd[1]: Stopped uncron.service - Command Queue Service.
```

**Comment by dd010101** [comment] 2024-08-04 10:12
Yep, VyOS team did break the uncron by latest changes 3 days ago, I will look into it.

**Comment by dd010101** [comment] 2024-08-04 11:12
It should be fixed now https://github.com/dd010101/vyos-jenkins/commit/3631bcca58b34d3857d42b8c5941ea2234c0be89.

**Please rerun the 4 step and up and please give feedback if the fix is working.**

---

It doesn't help that VyOS team uses hardcoded (and wrong) paths in their source code, thus to fix the permission issue properly I did need to rewrite the hardcoded path in the uncron ocaml source code as well, oh well.

**Comment by marekm72** [comment] 2024-08-04 14:12
I can confirm it works fine now, sagitta iso build completed.
This time started from scratch in a Debian 12 cloud image from XO Hub template, to test it as a faster way to install a new Debian VM on XCP-NG + XOA (this uses the same "ifupdown" as standard Debian, no surprises with dummy0 here).
BTW, if you want to open an issue in their uncron repo but are blocked, perhaps I could do that for you.

**Comment by dd010101** [comment] 2024-08-04 14:42
👍 My test was also successful for both branches (based on clean system). I also tried to update existing/broken uncron and that did also work. I'm using VM with snapshots to revert to clean-installation, so I don't need to reinstall the OS every time, but it still takes long time (1-2 hours) to build all packages and both ISOs.

I did also today finally reproduced the GitHub server issue when my CPU was overloaded in the provisioning phase, so I added concurrency limiting to slow the provisioning down since otherwise Jenkins spawns way too many threads regardless of how many workers it has. This may help with the reliability.

My account is banned everywhere but nothing stops me from creating new one if I really want to but I don't have any motivation anyway. My free time is too limited in order to contribute to project that tries it's best to stop me from doing so... 😄

**Closed by dd010101** 2024-08-04 14:42 UTC

**Comment by marekm72** [comment] 2024-08-04 15:35
One motivation I can see is that it may be more work to maintain later if our and their codebases diverge too much.  They are upstream for uncron but debianized it which looks like a good thing, and their own comment about it being hacky means they could be open to improvements.  One person with whom we've had some disagreement (to put it mildly) doesn't necessarily make the whole project bad, and the uncron changes were made by a different person.
