### ISSUE TITLE
01-prereqs.sh fails on Debian cloud images

### ISSUE THREAD

**Issue by RSully** [dd010101/vyos-jenkins#41] opened 2024-07-26 21:13 UTC
Hi, I create a fresh VM for running this based off of the Debian 12 cloud image (https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-amd64-20240717-1811.qcow2) and I am failing on the first step. It looks like `ifup` is not found.

```
root@vyosbuilder01:/opt/vyos-jenkins# ./1-prereqs.sh 
                                                        
#################################################
# Unofficial VyOS package mirror installer v1.0 #
#################################################

-- Currently executing '1-prereqs.sh' --

[ OK ] Updated apt sources.
[ OK ] cURL is already installed.
[ OK ] Jenkins sources.list.d files has been set up.
[ OK ] Docker sources.list.d files has been set up.
[ OK ] Updated apt sources.
[ OK ] Created jenkins group.
[ OK ] Created jenkins user.
[ OK ] Installed Reprepro.
[ OK ] Installed Jq.
[ OK ] Installed Java.
[ OK ] Installed Git.
[ OK ] Installed OCaml.
[ OK ] SSH is already installed.
[ OK ] Installed Jenkins.
[ OK ] Installed AptCacherNg.
[ OK ] GnuPG is already installed.
[ OK ] Installed XMLStarlet.
[ OK ] Installed Docker.
[ OK ] Installed NGINX.
[ OK ] Added Jenkins user to Docker group.
[ OK ] Restarted Jenkins.
[ OK ] Network interface dummy0 has been configured.
[    ] Starting network interface dummy0...
./auto/helper-logic: line 158: ifup: command not found
[ !! ] Failed to start network interface dummy0.
```

**Comment by RSully** [comment] 2024-07-26 21:19
It looks like the Debian 12 cloud images may be using Netplan for network interfaces which treats things a bit differently, but further digging might be required

**Comment by RSully** [comment] 2024-07-26 22:48
It also should be noted that this script doesn't handle the case where `interfaces.d` does not exist at all, and it ends up (incorrectly) creating a file named `interfaces.d` instead of copying the file into the folder:

```
root@vyosbuilder01:/etc/network# ls -la
total 20
drwxr-xr-x  4 root root 4096 Jul 26 21:10 .
drwxr-xr-x 86 root root 4096 Jul 26 21:10 ..
drwxr-xr-x  2 root root 4096 Jul 17 04:37 if-pre-up.d
drwxr-xr-x  2 root root 4096 Jul 17 04:37 if-up.d
-rw-r--r--  1 root root  106 Jul 26 21:10 interfaces.d
root@vyosbuilder01:/etc/network# cat interfaces.d 
auto dummy0
iface dummy0 inet static
    address 172.17.17.17/32
    pre-up ip link add dummy0 type dummy
```

**Comment by RSully** [comment] 2024-07-27 06:02
I can successfully create the interface this way:

```
ip link add dummy0 type dummy
ip addr add 172.17.17.17/32 dev dummy0
ip link set dummy0 up
```

And get:

```
root@vyosbuilder01:/etc/network# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
<SNIP>
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:76:f1:6e:2a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 92:c7:35:41:77:31 brd ff:ff:ff:ff:ff:ff
    inet 172.17.17.17/32 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::90c7:35ff:fe41:7731/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by RSully** [comment] 2024-07-27 06:19
Netplan supports dummy interfaces as of 0.107 (https://bugs.launchpad.net/netplan/+bug/1774203), however Debian 12 repos are currently at 0.106.

Once Netplan is updated, I think this could be leveraged by writing to `/etc/netplan/60-dummy0.yaml`:

```
network:
  version: 2
  dummy-devices:
    dummy0:
      addresses:
        - 172.17.17.17/32
```

In the meantime, directly using SystemD networking is required, as shown here: https://askubuntu.com/a/1058802

This is successful for me:

```
root@vyosbuilder01:/etc/systemd/network# ls -la
total 16
drwxr-xr-x 2 root root 4096 Jul 27 06:17 .
drwxr-xr-x 5 root root 4096 Jul 17 04:37 ..
-rw-r--r-- 1 root root   33 Jul 27 06:17 10-dummy0.netdev
-rw-r--r-- 1 root root   56 Jul 27 06:17 20-dummy0.network
root@vyosbuilder01:/etc/systemd/network# cat 10-dummy0.netdev 
[NetDev]
Name=dummy0
Kind=dummy

root@vyosbuilder01:/etc/systemd/network# cat 20-dummy0.network 
[Match]
Name=dummy0

[Network]
Address=172.17.17.17/32
```

Result:

```
root@vyosbuilder01:~# ip addr
<SNIP>
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether a2:85:d1:2a:ea:40 brd ff:ff:ff:ff:ff:ff
    inet 172.17.17.17/32 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::a085:d1ff:fe2a:ea40/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:72:8b:43:e9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by dd010101** [comment] 2024-07-27 06:55
We assume regular Debian installation thus this kind of installation is completely untested and unsupported. As I understand this the cloud image is configured for use with infrastructure where you handle network configuration via automated cloud-init-like tools thus not really suited for this kind of deployment where you want your own user-runtime-defined networking.

Is there a reason why would you use this cloud image? Why would you not use regular Debian instead?

The Debian has already great networking frontend called ifupdown and I don't see the point by replacing by something else for user use-case. That's the cause of both of those issues - both the ifup missing and the mishap with /etc/networking/interfaces.d - those things should exist and don't because your system doesn't have the ifupdown networking.

**Comment by RSully** [comment] 2024-07-27 18:38
> We assume regular Debian installation thus this kind of installation is completely untested and unsupported. As I understand this cloud image is configured for use with infrastructure where you handle network configuration via automated cloud-init-like tools thus not really suited for this kind of deployment where you want your own user-runtime-defined networking.
> 
> Is there a reason why would you use this cloud image? Why would you not use regular Debian instead?

Totally understand that this is an untested use-case right now.

I think it would be really beneficial to get support for Debian's [cloud images](https://wiki.debian.org/Cloud/) added to this project. These images are supplied directly from the Debian project. To my knowledge, these are the same type of images that would be used if you spun up a VM on AWS, so having support would allow people to spin up a cloud VM and build their images super easily. 

I personally use Debian's cloud images because I am running on a Proxmox cluster, and going from a cloud image to a usable VM mimics the way cloud providers provision systems, and IMO is actually much easier (and reproducible) than manually installing Debian. Especially because I can get the base system setup once as a template and clone it infinitely!

For reference, these are the steps I use to make a template in Proxmox from Debian's cloud image: https://gist.github.com/RSully/431cad726289d04bb3fa136dd8d360f8

> As I understand this cloud image is configured for use with infrastructure where you handle network configuration via automated cloud-init-like tools thus not really suited for this kind of deployment where you want your own user-runtime-defined networking.

This is both true and false. The images are designed for their "physical" interfaces to be configured via cloud-init. However, that doesn't stop tooling from creating additional interfaces. Installing Docker and other tools that touch the networking stack don't have problems, and the `docker0` interface came up without any issues. Additionally, I was able to get the `dummy0` interface to come up using the method I shared above. It isn't that it isn't possible / allowed, it just is a bit different. I think supporting both bare-metal Debian installs and cloud installs would be really beneficial.

I would be really curious to see if the method I used works on regular Debian installations (not just cloud images) because then this project could use that method and have it work everywhere. Otherwise, a bit of shell scripting could detect which method should be used. I'd love to hear your thoughts on this.

**Comment by dd010101** [comment] 2024-07-27 19:30
I don't see proper way to support cloud images since you demonstrated yourself that the networking frontend doesn't support dummy interfaces for now. The workaround via systemd surely works - the same for direct interface creation - but that's more hack than proper solution since that bypasses the network configuration of the system. Thus I can see only workarounds and no solution that would be in-line with the networking configuration of the cloud image.

Speaking of workaround - what if we installed ifupdown? I have no idea what happens but in theory it should work? Like you would use netplan for one thing and ifupdown for another? Not sure if ifupdown doesn't replace the netplan tho, that would break your networking... 

The docker example is misleading since docker doesn't use the user network configuration at all, it's all dynamic and created on fly.

Yes you totally can bypass the standard networking configuration on any Debian and do it in whatever other way you want but that's kind of not recommended. If your system has some kind of networking then you should use it and not try to bypass it... The fact it works doesn't mean it's good ideal... Imagine you want to debug such system where anyone uses their way of configuration stuff in any way just not the official way, that's creating uncessary complexity if you need to manage your networking (or anything) in multiple places via different tools.

**Comment by RSully** [comment] 2024-07-27 19:56
There may be some confusion here. `ifupdown` is only one of many front ends for Debian. This is no different than other networking frontends, like Netplan, systemd-networkd, NetworkManager, etc. Right now we're tied to one that happens to be included when you use the bare-metal Debian installer, but not included for cloud images. (I also believe Ubuntu is moving away from ifupdown as well.)

> I don't see proper way to support cloud images since you demonstrated yourself that the networking frontend doesn't support dummy interfaces for now.

As I showed, the cloud image has 2 networking front ends available out of the box: systemd-networkd and Netplan. They are both installed and running (I did **not** have to `systemctl start systemd-networkd` for example). The version of Netplan shipped with Debian 12 right now does not support dummy interfaces, but systemd-networkd does. 

It would be relatively simple to detect if we're on a cloud image and use the systemd-networkd configuration if we are, and use the ifupdown configuration if we aren't. There is nothing inherently wrong with this as far as I can tell. 

In addition, I am not so concerned with having this network configuration done by systemd-networkd and cloud-init's done by Netplan, since these VMs are single-purpose, and your scripts are well documented.

If we used your propose workaround of installing ifupdown on the cloud image (which I'm not sure will work, I did see a bug report about issues with ifupdown and cloud-init causing problems) I think we would be in an even worse place: then we have 3 frontends installed (systemd-networkd, netplan, and ifupdown) and configuration is still split between 2 frontends (Netplan and ifupdown). I think using systemd-networkd, which is included and enabled by default, is a much cleaner solution until Debian adopts the newer version of Netplan with this feature.

**Comment by dd010101** [comment] 2024-07-28 04:47
> Right now we're tied to one that happens to be included when you use the bare-metal Debian installer

I'm totally using regular Debian on tens of VMs right know so this description is bit misleading. The installation totally works just fine everywhere and basically majority of VM providers give you images based on the installation not the cloud image. I have no idea what AWS EC2 gives you, but that's irrelevant - we don't support AWS EC2, we support the most universal server OS there is - regular Debian.

> I also believe Ubuntu is moving away from ifupdown as well

That's the exact reason why to support single system / version to avoid such diverse environment.

There is important distinction to draw between regular package you install and these scripts - because these scripts install other software and rely on many default Debian configurations - this is the only reasonable way to do this. Since the setup is very far reaching, there is no way to make it self-contained where you just run it anyware, since it touches many different aspects.

There is also another stong argument for single unified environment - testing. I need to run all steps and build all packages (including large packages like kernels) to verify the installer works from base installation and if I need to do it multiple times to verify multiple systems, that's not cool.

> As I showed, the cloud image has 2 networking front ends available out of the box: systemd-networkd

You are bending the reality little - the netplan is using networkd for itself that's why it's there, I mean the networkd is everywhere even on regular Debian because it's core component of systemd, that's whole another topic though. Simply it seems as of now you can't have system without networkd... 

> I would be really curious to see if the method I used works on regular Debian installations (not just cloud images) because then this project could use that method and have it work everywhere. 

That's why this is bonkers. Let's just use networkd/systemd for everything even if we have ifupdown... 🙄

> It would be relatively simple to detect if we're on a cloud image and use the systemd-networkd configuration.

Sure, this is question of should we more than can we.

Is this the only difference though? That's something you could tell - does it work (creates ISO) if you create the dummy0 on the side yourself?

> I think we would be in an even worse place: then we have 3 frontends installed (systemd-networkd, netplan, and ifupdown

Yes that's a mess of your choice - if you use image with netplan that isn't ready yet then don't be surprised 😄, but regular Debian doesn't need to be compromised as well because of it.

Whatever... Did you try what happens if you install ifupdown? Could you try? For the science! Adding single apt install would be even easier than detecting if you have ifupdown and then using alternative interface definition and handling commands...

**Comment by jkvint** [comment] 2024-07-28 14:55
Add to file /etc/network/interfaces string

`source /etc/network/interfaces.d/*`

**Comment by RSully** [comment] 2024-07-28 17:15
> Is this the only difference though? That's something you could tell - does it work (creates ISO) if you create the dummy0 on the side yourself?

Yes, when I create dummy0 using systemd-networkd as I showed above, the entire rest of the process is successful. I was able to build a 1.3.8 image without any issues, and I just booted it on my router successfully.

**Comment by RSully** [comment] 2024-07-28 17:22
To address the rest of your comment: I'm using Debian 12, too. The AMIs that the Debian project provides to AWS EC2 are Debian, same with GCP, Azure, Openstack, etc.. They are all well documented: https://wiki.debian.org/Cloud/

If systemd-networkd is the lowest common denominator between all of these images, why wouldn't we use that instead of ifupdown? If it exists on the cloud images, and it exists on your standard install, it would work for everyone. Especially since the rest of the build process succeeds without any further changes, this might be good to explore.

**Comment by dd010101** [comment] 2024-07-29 06:51
I was wrong: `WARNING: systemd-networkd is not running, output will be incomplete.`. The regular Debian doesn't have networkd enabled by default, it's there but disabled.

```
systemctl status systemd-networkd
○ systemd-networkd.service - Network Configuration
     Loaded: loaded (/lib/systemd/system/systemd-networkd.service; disabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
             man:org.freedesktop.network1(5)
```

Thus there is no common configuration that would work for both. We can only add conditional networkd profile and that's annoying since then I need both Debian versions to do all testing.

**Comment by dd010101** [comment] 2024-07-29 10:07
And so I did add the conditional networkd profile https://github.com/dd010101/vyos-jenkins/commit/84e5277f3f2f3c713cf988143da173c8ae45fc4d but take it as untested/experimental platform - I will not verify/test the build on the cloud image unless there is significant demand since that requires lot of extra time/resources to do.

**Closed by dd010101** 2024-07-29 10:07 UTC

**Comment by RSully** [comment] 2024-07-29 19:12
Got it, really appreciate that! 

It really is unfortunate none of these methods are common to both images.

According to this thread I found on Reddit, there won't be any changes to this in Debian 13 so far either: https://www.reddit.com/r/debian/comments/1b8ytdb/netplan_in_trixietesting_and_systemdnetworkd/
